# Generated by Django 5.2.3 on 2025-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttransactionsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='merchanttransactionsmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
