# Generated by Django 5.2.3 on 2025-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_merchanttransactionsmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchanttransactionsmodel',
            options={'verbose_name': 'Merchant', 'verbose_name_plural': 'Merchants'},
        ),
        migrations.AddField(
            model_name='merchanttransactionsmodel',
            name='payment_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
