# Generated by Django 5.2.3 on 2025-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_merchanttransactionsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttransactionsmodel',
            name='deal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
